export const INIT_SOCKET = 'INIT_SOCKET';
export const RECEIVE_DATA = 'RECEIVE_DATA';

export const DASHBOARD_SELECT_TAB = 'DASHBOARD_SELECT_TAB';

export const GENERAL_REFRESH_VENTILATOR_POSITION = 'GENERAL_REFRESH_VENTILATOR_POSITION';
export const GENERAL_REFRESH_VENTILATOR_SPEED = 'GENERAL_REFRESH_VENTILATOR_SPEED';
export const GENERAL_REFRESH_AIR_CONDITIONING = 'GENERAL_REFRESH_AIR_CONDITIONING';
export const GENERAL_REFRESH_AIR_RECIRCULATION = 'GENERAL_REFRESH_AIR_RECIRCULATION';
export const GENERAL_REFRESH_HAZARD_LIGHTS = 'GENERAL_REFRESH_HAZARD_LIGHTS';
export const GENERAL_REFRESH_DOOR_LOCKS = 'GENERAL_REFRESH_DOOR_LOCKS';
export const GENERAL_REFRESH_DEFROST = 'GENERAL_REFRESH_DEFROST';
export const GENERAL_REFRESH_VALUES = 'GENERAL_REFRESH_VALUES';

export const ADVANCED_LOG = 'ADVANCED_LOG';
export const ADVANCED_CHECK_UPDATE = 'ADVANCED_CHECK_UPDATE';
export const ADVANCED_CHECKED_UPDATE = 'ADVANCED_CHECKED_UPDATE';
export const ADVANCED_START_UPDATE = 'ADVANCED_START_UPDATE';
export const ADVANCED_UPDATED = 'ADVANCED_UPDATED';